name: spdcb_timer_new
description: New Version of SPDCB Timer, all on Flutter

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_colorpicker: ^0.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family:  CubingIcons
      fonts:
        - asset: fonts/CubingIcons.ttf
