name: spdcb_timer_new
description: New Version of SPDCB Timer, all on Flutter

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_colorpicker: ^0.2.6
  dynamic_theme: ^1.0.1
  js: ^0.6.1+1
  path_provider: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family:  CubingIcons
      fonts:
        - asset: fonts/CubingIcons.ttf
