/// Flutter icons CubingIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CubingIcons
///      fonts:
///       - asset: fonts/CubingIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CubingIcons {
  CubingIcons._();

  static const fontFamily = 'CubingIcons';

  static const IconData e222 = const IconData(0xe800, fontFamily: fontFamily);
  static const IconData e333 = const IconData(0xe801, fontFamily: fontFamily);
  static const IconData e333bf = const IconData(0xe802, fontFamily: fontFamily);
  static const IconData e333fm = const IconData(0xe803, fontFamily: fontFamily);
  static const IconData e333wf = const IconData(0xe804, fontFamily: fontFamily);
  static const IconData e333mbf = const IconData(0xe805, fontFamily: fontFamily);
  static const IconData e333oh = const IconData(0xe806, fontFamily: fontFamily);
  static const IconData e444 = const IconData(0xe807, fontFamily: fontFamily);
  static const IconData e444bf = const IconData(0xe808, fontFamily: fontFamily);
  static const IconData e555 = const IconData(0xe809, fontFamily: fontFamily);
  static const IconData e555bf = const IconData(0xe80a, fontFamily: fontFamily);
  static const IconData e666 = const IconData(0xe80b, fontFamily: fontFamily);
  static const IconData e777 = const IconData(0xe80c, fontFamily: fontFamily);
  static const IconData eClock = const IconData(0xe80d, fontFamily: fontFamily);
  static const IconData eMinx = const IconData(0xe80e, fontFamily: fontFamily);
  static const IconData ePyram = const IconData(0xe80f, fontFamily: fontFamily);
  static const IconData eSkewb = const IconData(0xe810, fontFamily: fontFamily);
  static const IconData eSq1 = const IconData(0xe811, fontFamily: fontFamily);
}
